### ISSUE TITLE
Email notifications don't work

### ISSUE THREAD

**Issue by greendog99** [linuxkidd/coachproxy-os#6]
Previously, the e-mail node was configured to use the CoachProxy.com SMTP server to deliver messages. For CoachProxyOS, a new method needs to be worked out. This new system should also allow users to send a test e-mail to confirm their settings work.

**Comment by greendog99** [comment]
The SMTP node for Node-RED requires entering the SMTP server info into the node editor, so it probably won't be useful for a generic user config. Might need to configure the mailer info directly in Linux.

I've switched to using the Pushover app for notifications, as I find it more reliable and real-time than email notifications (I have some Pushover code stubbed out in the Open Source version). However, I know most folks are used to email so it would be ideal to have that as an option too.

**Comment by greendog99** [comment]
Have successfully tested this with the https://flows.nodered.org/node/node-red-contrib-simple-sendmail module. Now just need to package it up so users can enter their SMTP server information.

**Comment by cterwilliger** [comment]
Cool.  I've been using the smtp node.  I'll switch over to sendmail and test.  I fleshed out your Pushover stubs and have been using that also.  Works great.

**Comment by greendog99** [comment]
FYI a new SD card image for release v1.1 has been uploaded to the https://github.com/rvc-proxy/coachproxy-os/releases page.
